name: Rust

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: "aarch64-unknown-linux-gnu,x86_64-unknown-linux-gnu"
    - name: Run formatting check.
      run: cargo fmt --check
    - name: Run clippy check.
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Test
      run: cargo test --all-targets --all-features
